name: FAST-B_1*4_To-KonViD-1k
num_epochs: 25 #20
l_num_epochs: 5 #10
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 12
num_workers: 6
split_seed: 42

wandb:
    project_name: VQA_Experiments_2022

data:
    train:
        type: FusionDataset
        args:
            phase: test
            anno_file: ./examplar_data_labels/KoNViD/labels.txt
            data_prefix: /data/ethan/KoNViD/
            sample_types:
                fragments:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 1
    val:
        type: FusionDataset
        args:
            phase: test
            anno_file: ./examplar_data_labels/KoNViD/labels.txt
            data_prefix: /data/ethan/KoNViD/
            sample_types:
                fragments:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 4



model:
    type: DiViDeAddEvaluator
    args:
        backbone:
            fragments:
                checkpoint: false
                pretrained: 
        backbone_size: swin_tiny_grpb
        backbone_preserve_keys: fragments
        divide_head: false
        vqa_head:
            in_channels: 768
            hidden_channels: 64
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05
        
# load_path: ./pretrained_weights/FAST_VQA_B_1_4.pth
load_path: ./pretrained_weights/FAST-B_1*4_To-KonViD-1k_val_s_dev_v0.1.pth
test_load_path: 

pretrained_clip: true
clip_lr_mult: 2
